### ISSUE TITLE
重新启动后出现了问题

### ISSUE THREAD

**Issue by RAINighty** [Colerar/bikkuri#2]
10-24T19:23:58.124 - I [nioEventLoopGroup-2-1] [net.mamoe.mirai.internal.utils.Log4jLoggerAdapter] >>> Bot cancelled: Bot closed
10-24T19:23:58.123 - E [main] [net.mamoe.mirai.internal.utils.Log4jLoggerAdapter] >>> null
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2188206043), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:309)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
10-24T19:23:58.127 - I [main] [net.mamoe.mirai.internal.utils.Log4jLoggerAdapter] >>> mirai-console started successfully.

使用TxCaptchaHelper，然后登陆时出现了这个问题

**Comment by Colerar** [comment]
属于 Mirai 问题。可自行查看 [Mirai](https://github.com/mamoe/mirai) 2298 号 issue。

稍后会发一个使用 Mirai 2.13.0-RC.2 的更新。

**Comment by RAINighty** [comment]
了解，感谢

**Comment by Colerar** [comment]
已发布：https://github.com/Colerar/bikkuri/releases/tag/v1.1.1

**Comment by RAINighty** [comment]
更新最新版本后问题依然存在，2298号issue里给出的解决方案不起作用

**Comment by Colerar** [comment]
个人猜测此问题为 QQ 限制。并且和近期中华人民共和国知名的政治会议有关。因为 QQ 的 Google Play 版这段时间也不能登录。

删缓存，删 device.json，并在本地登录可能会解决此问题。

**Comment by RAINighty** [comment]
> 个人猜测此问题为 QQ 限制。并且和近期中华人民共和国知名的政治会议有关。因为 QQ 的 Google Play 版这段时间也不能登录。
> 
> 删缓存，删 device.json，并在本地登录可能会解决此问题。

可能是，删缓存删device.json都试过了，但是不起作用

**Comment by RAINighty** [comment]
> 个人猜测此问题为 QQ 限制。并且和近期中华人民共和国知名的政治会议有关。因为 QQ 的 Google Play 版这段时间也不能登录。
> 
> 删缓存，删 device.json，并在本地登录可能会解决此问题。

本地也试过了不行，应该就是会的事了
